name: Rust Tests

on:
  push:
    branches: [ "main", "release" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
    
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1.12.0
      with:
        toolchain: stable
        cache: true
    
    - name: Install system dependencies (macOS)
      run: |
        # macOS dependencies if needed
        echo "macOS runner setup complete"

    - name: Build
      run: cargo build --verbose

    - name: Run Tests
      run: cargo test --verbose --all-features
  
  lint:
    name: Lint
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4.2.2
    
    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1.12.0
      with:
        toolchain: stable
        components: rustfmt, clippy
        cache: true
      
    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Lint with Clippy
      run: cargo clippy --all-features --all-targets -- -D warnings 